# Generated by Django 3.2.9 on 2021-11-25 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование проекта')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(verbose_name='Дата завершения проекта')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Роли пользователей',
                'verbose_name_plural': 'Роли пользователей',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата создания задачи')),
                ('todo_text', models.TextField(verbose_name='Содержание задачи')),
                ('end_date', models.DateField(verbose_name='Дата завершения задачи')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
                ('name_project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo.projects')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
            ],
            options={
                'verbose_name': 'Задачи проекта',
                'verbose_name_plural': 'Задачи проекта',
                'db_table': 'Todo',
            },
        ),
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
                ('name_project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo.projects')),
                ('name_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo.roles')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участники проекта',
                'verbose_name_plural': 'Участники проекта',
                'db_table': 'ProjectUsers',
            },
        ),
    ]
